### PR TITLE
Fix travis and run the tests also on Plone 5.2

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Review by reinhardt — APPROVED** [review]

**Comment by ale-rt** [comment]
Unluckily we cannot merge this one:
image

@hvelarde I think you have the power to merge this and maybe to remove this protection rule which seems to be to strict for a collective package...

**Comment by ale-rt** [comment]
Thanks @hvelarde!

**Comment by hvelarde** [comment]
IMO, removing branch protection is a bad idea; check:

https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests

**Comment by ale-rt** [comment]
Ok for the branch protection, but at least extend the number of authorized users who can do that!

**Comment by hvelarde** [comment]
seems to be fixed now; check: https://github.com/collective/Products.MemcachedManager/settings/access

**Comment by ale-rt** [comment]
Let's see, I cannot access https://github.com/collective/Products.MemcachedManager/settings/access because I have not enough privileges ;)

**Comment by hvelarde** [comment]
now you can :-)

**Comment by ale-rt** [comment]
I see you added me to the collective staff group but I still have no power on this repo!
Maybe there is some cache to break...

**Comment by hvelarde** [comment]
you're now Administrator of this package.

**Pull request merged**
